build(*): update all dependencies to newest version
Exception: esbuild stays @8 because 9/10 do not work with airbnb style guide (https://github.com/airbnb/javascript/issues/2961)